GET http://localhost:3000/Users

###
POST http://localhost:3000/register
Content-Type: application/json

{ "vnev": "yxc",
  "knev": "yxc",
  "email": "yxc",
  "pass": "yxc",
  "szuldatum": "1999-12-31T23:00:00Z",
  "neme": 0,
  "magassag": 143,
  "diet": [    ""  ],
  "goal": "weightloss",
  "permission": "user",
  "trainingplan": []
  }

###
GET http://localhost:3000/login
Content-Type: application/json

{
    "email": "yxc"
}